version: '3.8'

services:
  master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: shoppingmall
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    container_name: master
    volumes:
      - my-db-master:/var/lib/mysql
      - my-db-master:/var/lib/mysql-files
    networks:
      - mynet

  slave:
    build:
      context: ./
      dockerfile: slave/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: shoppingmall
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    container_name: slave
    volumes:
      - my-db-slave:/var/lib/mysql
      - my-db-slave:/var/lib/mysql-files
    networks:
      - mynet


  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - mynet
  cache:
    container_name: redis-cache
    image: redis
    ports:
      - 6480:6379
    restart: always
    networks:
      - mynet

  backend:
    container_name: backend
    image: zvyg1023/shopping-mall
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - master
      - slave
      - redis
      - cache
    networks:
      - mynet


volumes:
  my-db-master:
  my-db-slave:

networks:
  mynet:
    driver: bridge


  #  master:
  #    container_name: master
  #    image: mysql
  #    ports:
  #      - 3306:3306
  #    environment:
  #      MYSQL_ROOT_PASSWORD: 1234
  #      MYSQL_DATABASE: shoppingmall
  #    restart: always
  #    networks:
  #      - mynet
  #  slave:
  #    container_name: slave
  #    image: mysql
  #    ports:
  #      - 3307:3306
  #    environment:
  #      MYSQL_ROOT_PASSWORD: 1234
  #      MYSQL_DATABASE: shoppingmall
  #    restart: always
  #    networks:
  #      - mynet
