version: '3.8'

services:
  backend:
    container_name: backend
    image: zvyg1023/shopping-mall
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - master
      - slave
      - redis
      - cache
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
